contact_links:
  - name: 📚 Docs
    url: https://github.com/BetaHuhn/metadata-scraper#-usage
    about: Checkout metadata-scraper's documentation before you open an issue.
  - name: 📖 Examples
    url: https://github.com/BetaHuhn/metadata-scraper#-examples
    about: Here are a few examples on how to use metadata-scraper.